completed helm and added config utils
CyCognito/intel471-feed-reporter pull request #1
Opened 2022-06-27 14:38 UTC by idoabelman

2022-06-28 07:49 UTC, shiranpoz requested changes

2022-06-28 07:49 UTC, shiranpoz commented on helm/feed_reporter/templates/cronjob-feed-reporter.yaml
> +            image: eu.gcr.io/cyco-main/intel471-feed-reporter
plz add image tag and put it in values file. teamcity will update it after each build

2022-06-28 07:49 UTC, shiranpoz commented on helm/feed_reporter/templates/cronjob-feed-reporter.yaml
> +            image: eu.gcr.io/cyco-main/intel471-feed-reporter
image itself can be a value as well (it doesn't get set)

2022-06-28 07:49 UTC, shiranpoz commented on helm/feed_reporter/values.yaml
> +
add "tag" at top level (can be latest by def)

2022-07-03 09:49 UTC, jefimm commented
Please make sure the helm/... is named helm/intel471_feed_reporter and not feed_reporter

2022-07-03 10:29 UTC, jefimm approved these changes

2022-07-03 10:30 UTC, merged